### ISSUE TITLE
Core UI layout and functionality for puzzle scene

### ISSUE THREAD

**Issue by nourgaser** [Charged-Entertainment/Charged-Learning#6]
**Tasks needed:**
- [x] Tools sidebar on the left
- [x] Available components sidebar on the right
- [x] Top 'controls' bar with control buttons and level title
- [x] Bottom bar/terminal for text output (debugging/level submission)

![Image](https://user-images.githubusercontent.com/54468523/211804204-a91b3b9e-f8dc-41c6-8e2f-2d83f918be27.png)

**Comment by nourgaser** [comment]
Merged. https://github.com/Charged-Entertainment/Charged-Learning/commit/7d7ec6d1f61cf30d0f6ed5d72e34d2eb8858b51a
